In [58]:
import pandas as pd
import numpy as np
import tensorflow as tf
import keras
from keras import layers
from typing import Final
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [59]:
window_size: Final[int] = 1

EPOCHS: Final[int] = 50
BATCH_SIZE: Final[int] = 32

In [61]:
df = pd.read_csv("DailyDelhiClimateTrain.csv")

df['date'] = pd.to_datetime(df['date'])
print(f"Shape: {df.shape}")

display(df)

Shape: (1462, 5)

           date   meantemp    humidity  wind_speed  meanpressure
0    2013-01-01  10.000000   84.500000    0.000000   1015.666667
1    2013-01-02   7.400000   92.000000    2.980000   1017.800000
2    2013-01-03   7.166667   87.000000    4.633333   1018.666667
3    2013-01-04   8.666667   71.333333    1.233333   1017.166667
4    2013-01-05   6.000000   86.833333    3.700000   1016.500000
...         ...        ...         ...         ...           ...
1457 2016-12-28  17.217391   68.043478    3.547826   1015.565217
1458 2016-12-29  15.238095   87.857143    6.000000   1016.904762
1459 2016-12-30  14.095238   89.666667    6.266667   1017.904762
1460 2016-12-31  15.052632   87.000000    7.325000   1016.100000
1461 2017-01-01  10.000000  100.000000    0.000000   1016.000000

[1462 rows x 5 columns]

In [62]:
df.info()
print(f"\nduplicates = {df.duplicated().sum()}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1462 entries, 0 to 1461
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1462 non-null   datetime64[ns]
 1   meantemp      1462 non-null   float64
 2   humidity      1462 non-null   float64
 3   wind_speed    1462 non-null   float64
 4   meanpressure  1462 non-null   float64
dtypes: datetime64[ns](1), float64(4)
memory usage: 57.2 KB

duplicates = 0

In [63]:
fraction_missing: int = 0.1

mask = np.random.rand(*df.shape) < fraction_missing
df.loc[:, list(df.columns)][mask] = np.nan

In [64]:
df.interpolate(method='linear', inplace=True)

In [65]:
numeric_cols: list = df.select_dtypes(include=[np.number]).columns

noise = np.random.normal(0, 0.02, df[numeric_cols].shape)
df[numeric_cols] = df[numeric_cols] + noise

In [72]:
series = df["humidity"].values.reshape(-1, 1)
scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(series)

In [73]:
def get_dataset(data, window_size):
    x, y = [], []
    for i in range(len(data) - window_size - 1):
        x.append(data[i:i + window_size])
        y.append(data[i + window_size + 1])
    return np.array(x), np.array(y)

x, y = get_dataset(data_scaled, window_size)
x = x[..., None]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [74]:
rnn_model = keras.Sequential([
    layers.Input(shape=(window_size, 1)),
    layers.SimpleRNN(64),
    layers.Dense(1)
])
rnn_model.compile(optimizer='adam', loss='mse', metrics=['mae'])
history = rnn_model.fit(
    x_train, 
    y_train, 
    epochs=EPOCHS, 
    batch_size=BATCH_SIZE, 
    validation_data=(x_test, y_test)
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
Epoch 1/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0250 - mae: 0.1236 - val_loss: 0.0150 - val_mae: 0.0931
Epoch 2/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0144 - mae: 0.0936 - val_loss: 0.0150 - val_mae: 0.0933
Epoch 3/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0142 - mae: 0.0931 - val_loss: 0.0156 - val_mae: 0.0941
Epoch 4/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0142 - mae: 0.0927 - val_loss: 0.0158 - val_mae: 0.0944
Epoch 5/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0142 - mae: 0.0925 - val_loss: 0.0155 - val_mae: 0.0936
Epoch 6/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0142 - mae: 0.0924 - val_loss: 0.0156 - val_mae: 0.0938
Epoch 7/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0142 - mae: 0.0927 - val_loss: 0.0164 - val_mae: 0.0960
Epoch 8/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0142 - mae: 0.0920 - val_loss: 0.0153 - val_mae: 0.0933
Epoch 9/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0142 - mae: 0.0924 - val_loss: 0.0153 - val_mae: 0.0933
Epoch 10/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0141 - mae: 0.0920 - val_loss: 0.0154 - val_mae: 0.0934
Epoch 11/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0143 - mae: 0.0933 - val_loss: 0.0153 - val_mae: 0.0933
Epoch 12/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0141 - mae: 0.0920 - val_loss: 0.0161 - val_mae: 0.0953
Epoch 13/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0143 - mae: 0.0927 - val_loss: 0.0152 - val_mae: 0.0935
Epoch 14/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0142 - mae: 0.0926 - val_loss: 0.0157 - val_mae: 0.0941
Epoch 15/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0142 - mae: 0.0925 - val_loss: 0.0161 - val_mae: 0.0950
Epoch 16/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0143 - mae: 0.0925 - val_loss: 0.0152 - val_mae: 0.0937
Epoch 17/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0143 - mae: 0.0930 - val_loss: 0.0185 - val_mae: 0.1027
Epoch 18/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0146 - mae: 0.0933 - val_loss: 0.0159 - val_mae: 0.0944
Epoch 19/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0142 - mae: 0.0925 - val_loss: 0.0155 - val_mae: 0.0935
Epoch 20/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0143 - mae: 0.0927 - val_loss: 0.0154 - val_mae: 0.0935
Epoch 21/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0141 - mae: 0.0921 - val_loss: 0.0154 - val_mae: 0.0948
Epoch 22/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0144 - mae: 0.0929 - val_loss: 0.0154 - val_mae: 0.0934
Epoch 23/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0143 - mae: 0.0931 - val_loss: 0.0155 - val_mae: 0.0936
Epoch 24/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0142 - mae: 0.0923 - val_loss: 0.0152 - val_mae: 0.0933
Epoch 25/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0142 - mae: 0.0922 - val_loss: 0.0153 - val_mae: 0.0933
Epoch 26/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0142 - mae: 0.0929 - val_loss: 0.0152 - val_mae: 0.0934
Epoch 27/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0142 - mae: 0.0928 - val_loss: 0.0152 - val_mae: 0.0940
Epoch 28/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0143 - mae: 0.0933 - val_loss: 0.0156 - val_mae: 0.0938
Epoch 29/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0144 - mae: 0.0932 - val_loss: 0.0152 - val_mae: 0.0939
Epoch 30/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0143 - mae: 0.0928 - val_loss: 0.0155 - val_mae: 0.0936
Epoch 31/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0142 - mae: 0.0922 - val_loss: 0.0152 - val_mae: 0.0935
Epoch 32/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0142 - mae: 0.0927 - val_loss: 0.0152 - val_mae: 0.0933
Epoch 33/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0141 - mae: 0.0921 - val_loss: 0.0153 - val_mae: 0.0933
Epoch 34/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0141 - mae: 0.0923 - val_loss: 0.0153 - val_mae: 0.0934
Epoch 35/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0143 - mae: 0.0932 - val_loss: 0.0153 - val_mae: 0.0933
Epoch 36/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0142 - mae: 0.0920 - val_loss: 0.0157 - val_mae: 0.0940
Epoch 37/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0143 - mae: 0.0931 - val_loss: 0.0154 - val_mae: 0.0934
Epoch 38/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0142 - mae: 0.0930 - val_loss: 0.0158 - val_mae: 0.0943
Epoch 39/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0143 - mae: 0.0928 - val_loss: 0.0157 - val_mae: 0.0940
Epoch 40/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0143 - mae: 0.0922 - val_loss: 0.0152 - val_mae: 0.0937
Epoch 41/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0142 - mae: 0.0927 - val_loss: 0.0153 - val_mae: 0.0933
Epoch 42/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0144 - mae: 0.0929 - val_loss: 0.0153 - val_mae: 0.0941
Epoch 43/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0143 - mae: 0.0931 - val_loss: 0.0156 - val_mae: 0.0938
Epoch 44/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0144 - mae: 0.0934 - val_loss: 0.0152 - val_mae: 0.0937
Epoch 45/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0141 - mae: 0.0920 - val_loss: 0.0154 - val_mae: 0.0934
Epoch 46/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0142 - mae: 0.0925 - val_loss: 0.0152 - val_mae: 0.0936
Epoch 47/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0142 - mae: 0.0927 - val_loss: 0.0152 - val_mae: 0.0936
Epoch 48/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0143 - mae: 0.0931 - val_loss: 0.0158 - val_mae: 0.0942
Epoch 49/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0144 - mae: 0.0939 - val_loss: 0.0153 - val_mae: 0.0933
Epoch 50/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0142 - mae: 0.0928 - val_loss: 0.0152 - val_mae: 0.0933

In [81]:
def evaluate_model(model, x_test, y_test):
    predictions = model.predict(x_test)
    return {
        "MSE": mean_squared_error(y_test, predictions),
        "MAE": mean_absolute_error(y_test, predictions),
        "R2": r2_score(y_test, predictions),
    }

In [ ]:
print(evaluate_model(rnn_model, x_test, y_test))

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
{'MSE': 0.015241606652267713, 'MAE': 0.09329112528882623, 'R2': 0.5348193921785737}

In [ ]:
lstm_model = keras.Sequential([
    layers.Input(shape=(window_size, 1)),
    layers.LSTM(64),
    layers.Dense(1)
])
lstm_model.compile(optimizer='adam', loss='mse', metrics=['mae'])
history = lstm_model.fit(
    x_train, 
    y_train, 
    epochs=EPOCHS, 
    batch_size=BATCH_SIZE, 
    validation_data=(x_test, y_test)
)

Epoch 1/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.2307 - mae: 0.4391 - val_loss: 0.1555 - val_mae: 0.3615
Epoch 2/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0838 - mae: 0.2459 - val_loss: 0.0420 - val_mae: 0.1733
Epoch 3/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0253 - mae: 0.1277 - val_loss: 0.0183 - val_mae: 0.1059
Epoch 4/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0196 - mae: 0.1116 - val_loss: 0.0177 - val_mae: 0.1040
Epoch 5/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0191 - mae: 0.1102 - val_loss: 0.0174 - val_mae: 0.1030
Epoch 6/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0186 - mae: 0.1087 - val_loss: 0.0170 - val_mae: 0.1018
Epoch 7/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0182 - mae: 0.1075 - val_loss: 0.0168 - val_mae: 0.1010
Epoch 8/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0177 - mae: 0.1059 - val_loss: 0.0164 - val_mae: 0.0996
Epoch 9/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0172 - mae: 0.1042 - val_loss: 0.0162 - val_mae: 0.0988
Epoch 10/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0167 - mae: 0.1031 - val_loss: 0.0160 - val_mae: 0.0981
Epoch 11/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0163 - mae: 0.1015 - val_loss: 0.0157 - val_mae: 0.0969
Epoch 12/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0160 - mae: 0.1007 - val_loss: 0.0158 - val_mae: 0.0969
Epoch 13/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0157 - mae: 0.0993 - val_loss: 0.0156 - val_mae: 0.0962
Epoch 14/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0154 - mae: 0.0982 - val_loss: 0.0154 - val_mae: 0.0953
Epoch 15/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0152 - mae: 0.0972 - val_loss: 0.0154 - val_mae: 0.0950
Epoch 16/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0150 - mae: 0.0966 - val_loss: 0.0155 - val_mae: 0.0950
Epoch 17/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0148 - mae: 0.0958 - val_loss: 0.0152 - val_mae: 0.0943
Epoch 18/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0148 - mae: 0.0954 - val_loss: 0.0152 - val_mae: 0.0942
Epoch 19/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0146 - mae: 0.0948 - val_loss: 0.0156 - val_mae: 0.0946
Epoch 20/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0146 - mae: 0.0944 - val_loss: 0.0156 - val_mae: 0.0946
Epoch 21/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0145 - mae: 0.0939 - val_loss: 0.0154 - val_mae: 0.0941
Epoch 22/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0145 - mae: 0.0942 - val_loss: 0.0155 - val_mae: 0.0941
Epoch 23/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0146 - mae: 0.0939 - val_loss: 0.0155 - val_mae: 0.0942
Epoch 24/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0144 - mae: 0.0935 - val_loss: 0.0156 - val_mae: 0.0944
Epoch 25/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0144 - mae: 0.0934 - val_loss: 0.0153 - val_mae: 0.0939
Epoch 26/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0144 - mae: 0.0933 - val_loss: 0.0158 - val_mae: 0.0948
Epoch 27/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0144 - mae: 0.0932 - val_loss: 0.0156 - val_mae: 0.0943
Epoch 28/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0144 - mae: 0.0930 - val_loss: 0.0153 - val_mae: 0.0940
Epoch 29/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0145 - mae: 0.0936 - val_loss: 0.0155 - val_mae: 0.0940
Epoch 30/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0145 - mae: 0.0933 - val_loss: 0.0157 - val_mae: 0.0945
Epoch 31/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0144 - mae: 0.0932 - val_loss: 0.0158 - val_mae: 0.0947
Epoch 32/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0144 - mae: 0.0932 - val_loss: 0.0156 - val_mae: 0.0942
Epoch 33/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0144 - mae: 0.0930 - val_loss: 0.0154 - val_mae: 0.0943
Epoch 34/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0144 - mae: 0.0931 - val_loss: 0.0156 - val_mae: 0.0942
Epoch 35/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0144 - mae: 0.0931 - val_loss: 0.0154 - val_mae: 0.0943
Epoch 36/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0144 - mae: 0.0934 - val_loss: 0.0159 - val_mae: 0.0949
Epoch 37/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0144 - mae: 0.0929 - val_loss: 0.0157 - val_mae: 0.0944
Epoch 38/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0143 - mae: 0.0928 - val_loss: 0.0156 - val_mae: 0.0942
Epoch 39/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0144 - mae: 0.0929 - val_loss: 0.0157 - val_mae: 0.0945
Epoch 40/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0143 - mae: 0.0926 - val_loss: 0.0155 - val_mae: 0.0940
Epoch 41/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0143 - mae: 0.0929 - val_loss: 0.0157 - val_mae: 0.0943
Epoch 42/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0143 - mae: 0.0928 - val_loss: 0.0157 - val_mae: 0.0944
Epoch 43/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0144 - mae: 0.0929 - val_loss: 0.0157 - val_mae: 0.0945
Epoch 44/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0143 - mae: 0.0928 - val_loss: 0.0155 - val_mae: 0.0940
Epoch 45/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0143 - mae: 0.0928 - val_loss: 0.0155 - val_mae: 0.0939
Epoch 46/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0144 - mae: 0.0931 - val_loss: 0.0154 - val_mae: 0.0947
Epoch 47/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0145 - mae: 0.0936 - val_loss: 0.0156 - val_mae: 0.0941
Epoch 48/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0144 - mae: 0.0930 - val_loss: 0.0153 - val_mae: 0.0940
Epoch 49/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0143 - mae: 0.0928 - val_loss: 0.0157 - val_mae: 0.0943
Epoch 50/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0143 - mae: 0.0929 - val_loss: 0.0155 - val_mae: 0.0939

In [ ]:
print(evaluate_model(lstm_model, x_test, y_test))

12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step
MSE: 0.015456866152069829
MAE: 0.09390456726093326
R2: 0.5282495765914232

In [ ]:
gru_model = keras.Sequential([
    layers.Input(shape=(window_size, 1)),
    layers.GRU(64),
    layers.Dense(1)
])
gru_model.compile(optimizer='adam', loss='mse', metrics=['mae'])
history = gru_model.fit(
    x_train, 
    y_train, 
    epochs=EPOCHS, 
    batch_size=BATCH_SIZE, 
    validation_data=(x_test, y_test)
)

Epoch 1/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.1387 - mae: 0.3177 - val_loss: 0.0317 - val_mae: 0.1472
Epoch 2/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0231 - mae: 0.1208 - val_loss: 0.0185 - val_mae: 0.1068
Epoch 3/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0205 - mae: 0.1143 - val_loss: 0.0181 - val_mae: 0.1055
Epoch 4/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0193 - mae: 0.1108 - val_loss: 0.0176 - val_mae: 0.1037
Epoch 5/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0183 - mae: 0.1079 - val_loss: 0.0169 - val_mae: 0.1014
Epoch 6/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0174 - mae: 0.1050 - val_loss: 0.0161 - val_mae: 0.0986
Epoch 7/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0166 - mae: 0.1025 - val_loss: 0.0160 - val_mae: 0.0977
Epoch 8/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0159 - mae: 0.1000 - val_loss: 0.0155 - val_mae: 0.0960
Epoch 9/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0154 - mae: 0.0978 - val_loss: 0.0152 - val_mae: 0.0948
Epoch 10/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0150 - mae: 0.0965 - val_loss: 0.0151 - val_mae: 0.0941
Epoch 11/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0146 - mae: 0.0950 - val_loss: 0.0152 - val_mae: 0.0939
Epoch 12/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0145 - mae: 0.0941 - val_loss: 0.0158 - val_mae: 0.0948
Epoch 13/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0145 - mae: 0.0938 - val_loss: 0.0154 - val_mae: 0.0937
Epoch 14/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0143 - mae: 0.0932 - val_loss: 0.0158 - val_mae: 0.0946
Epoch 15/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0143 - mae: 0.0930 - val_loss: 0.0153 - val_mae: 0.0936
Epoch 16/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0143 - mae: 0.0929 - val_loss: 0.0154 - val_mae: 0.0937
Epoch 17/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0143 - mae: 0.0927 - val_loss: 0.0154 - val_mae: 0.0936
Epoch 18/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0142 - mae: 0.0927 - val_loss: 0.0154 - val_mae: 0.0937
Epoch 19/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0142 - mae: 0.0925 - val_loss: 0.0154 - val_mae: 0.0937
Epoch 20/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0142 - mae: 0.0926 - val_loss: 0.0160 - val_mae: 0.0950
Epoch 21/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0143 - mae: 0.0926 - val_loss: 0.0153 - val_mae: 0.0936
Epoch 22/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0142 - mae: 0.0926 - val_loss: 0.0155 - val_mae: 0.0938
Epoch 23/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0143 - mae: 0.0925 - val_loss: 0.0155 - val_mae: 0.0938
Epoch 24/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0143 - mae: 0.0924 - val_loss: 0.0152 - val_mae: 0.0936
Epoch 25/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0143 - mae: 0.0926 - val_loss: 0.0152 - val_mae: 0.0940
Epoch 26/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0142 - mae: 0.0925 - val_loss: 0.0152 - val_mae: 0.0936
Epoch 27/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0143 - mae: 0.0929 - val_loss: 0.0154 - val_mae: 0.0936
Epoch 28/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0142 - mae: 0.0923 - val_loss: 0.0156 - val_mae: 0.0939
Epoch 29/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0143 - mae: 0.0925 - val_loss: 0.0153 - val_mae: 0.0935
Epoch 30/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0143 - mae: 0.0929 - val_loss: 0.0153 - val_mae: 0.0945
Epoch 31/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0143 - mae: 0.0929 - val_loss: 0.0153 - val_mae: 0.0935
Epoch 32/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0142 - mae: 0.0928 - val_loss: 0.0156 - val_mae: 0.0938
Epoch 33/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0142 - mae: 0.0924 - val_loss: 0.0154 - val_mae: 0.0936
Epoch 34/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0143 - mae: 0.0928 - val_loss: 0.0153 - val_mae: 0.0935
Epoch 35/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0142 - mae: 0.0926 - val_loss: 0.0153 - val_mae: 0.0935
Epoch 36/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0143 - mae: 0.0928 - val_loss: 0.0153 - val_mae: 0.0935
Epoch 37/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0143 - mae: 0.0927 - val_loss: 0.0155 - val_mae: 0.0937
Epoch 38/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0143 - mae: 0.0929 - val_loss: 0.0153 - val_mae: 0.0935
Epoch 39/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0141 - mae: 0.0922 - val_loss: 0.0157 - val_mae: 0.0941
Epoch 40/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0142 - mae: 0.0928 - val_loss: 0.0155 - val_mae: 0.0936
Epoch 41/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0142 - mae: 0.0924 - val_loss: 0.0154 - val_mae: 0.0935
Epoch 42/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0142 - mae: 0.0926 - val_loss: 0.0153 - val_mae: 0.0935
Epoch 43/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0142 - mae: 0.0923 - val_loss: 0.0152 - val_mae: 0.0934
Epoch 44/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0142 - mae: 0.0928 - val_loss: 0.0153 - val_mae: 0.0934
Epoch 45/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0142 - mae: 0.0925 - val_loss: 0.0162 - val_mae: 0.0954
Epoch 46/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0143 - mae: 0.0927 - val_loss: 0.0165 - val_mae: 0.0962
Epoch 47/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0144 - mae: 0.0932 - val_loss: 0.0152 - val_mae: 0.0936
Epoch 48/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0142 - mae: 0.0929 - val_loss: 0.0153 - val_mae: 0.0934
Epoch 49/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0143 - mae: 0.0927 - val_loss: 0.0155 - val_mae: 0.0936
Epoch 50/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0142 - mae: 0.0926 - val_loss: 0.0153 - val_mae: 0.0934

In [ ]:
print(evaluate_model(gru_model, x_test, y_test))

12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step
MSE: 0.015340523779487723
MAE: 0.09340560521881155
R2: 0.5318003975007844

In [86]:
display(pd.DataFrame({'RNN': evaluate_model(rnn_model, x_test, y_test),
                      'LSTM': evaluate_model(lstm_model, x_test, y_test),
                      'GRU': evaluate_model(gru_model, x_test, y_test),
                    }))

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

          RNN      LSTM       GRU
MSE  0.015242  0.015457  0.015341
MAE  0.093291  0.093905  0.093406
R2   0.534819  0.528250  0.531800